#ifndef INFINI_OPS_ASCEND_ADD_RMS_NORM_KERNEL_CUSTOM_H_
#define INFINI_OPS_ASCEND_ADD_RMS_NORM_KERNEL_CUSTOM_H_

#ifdef INFINI_HAS_CUSTOM_KERNELS

#include <algorithm>
#include <cstdint>
#include <vector>

#include "acl/acl.h"
#include "aclnn/aclnn_base.h"
#include "aclnnop/aclnn_cast.h"
#include "ascend/common.h"
#include "ascend/workspace_pool_.h"
#include "base/add_rms_norm.h"
#include "operator.h"

// Forward-declare the generated AscendC kernel launch function.
// This symbol is provided by the `no_workspace_kernel` static library
// built from `ascend/custom/add_rms_norm/op_kernel/add_rms_norm.cpp`
// via `ascendc_library()`.
// `aclrtlaunch_*` symbol name is generated by `ascendc_library()` /
// `ascendc_add_operator()` and cannot be `PascalCase`d.
// NOLINTNEXTLINE(readability-identifier-naming)
extern "C" uint32_t aclrtlaunch_add_rms_norm(
    uint32_t block_dim, void* stream, void* x1, void* x2, void* weight, void* y,
    void* x_out, int64_t total_rows, int64_t dim_length,
    int64_t dim_length_align, int64_t former_num, int64_t former_length,
    int64_t tail_length, float eps, int64_t dtype_code);

namespace infini::ops {

// Custom AscendC fused `AddRmsNorm` kernel (implementation index 2).
//
// A single-kernel implementation that computes `residual_out = input + other`
// followed by `out = rms_norm(residual_out, weight, eps)` in one launch,
// avoiding the decomposed `aclnnAdd` + `aclnnRmsNorm` calls (index 0) or
// the fused `aclnnAddRmsNorm` call (index 1).  Migrated from the custom
// `RmsNorm` kernel (index 1 of `RmsNorm`).
//
// Select via `implementation_index=2` in Python:
//   `infini.ops.add_rms_norm(input, other, weight, eps, out, residual_out,
//                            implementation_index=2, stream=s)`.
//
// Requirements:
//   - Input last dimension must be 32-byte aligned (divisible by 16 for
//     `float16` or 8 for `float32`).  All standard LLM hidden dimensions
//     satisfy this.
//   - `weight` must have the same dtype as `input`.
//   - The custom kernel binary must be linked (`BUILD_ASCEND_CUSTOM=ON`).
template <>
class Operator<AddRmsNorm, Device::Type::kAscend, 2> : public AddRmsNorm {
 public:
  Operator(const Tensor input, const Tensor other, const Tensor weight,
           float eps, Tensor out, Tensor residual_out)
      : AddRmsNorm(input, other, weight, eps, out, residual_out),
        dtype_{input.dtype()} {
    assert((dtype_ == DataType::kFloat16 || dtype_ == DataType::kBFloat16 ||
            dtype_ == DataType::kFloat32) &&
           "`AddRmsNorm` custom kernel: `input` must be `fp16`, `bf16`, or "
           "`fp32`.");

    // 32-byte alignment on the last dimension — kernel relies on aligned
    // `DataCopyPad` loads/stores.
    int64_t align_elems = 32 / static_cast<int64_t>(kDataTypeToSize.at(dtype_));
    dim_length_align_ =
        ((static_cast<int64_t>(dim_) + align_elems - 1) / align_elems) *
        align_elems;
    assert(static_cast<int64_t>(dim_) == dim_length_align_ &&
           "`AddRmsNorm` custom kernel: last dimension must be 32-byte "
           "aligned.");

    total_rows_ =
        static_cast<int64_t>(batch_size_) * static_cast<int64_t>(nhead_);

    // The custom kernel always reads `weight` as fp32.  fp16 / bf16 inputs
    // trigger a lazy cast in `operator()` (guarded by `last_weight_ptr_`
    // so that the cast runs only when the weight pointer changes — model
    // weights are typically fixed after loading).
    if (dtype_ != DataType::kFloat32) {
      size_t fp32_bytes = static_cast<size_t>(dim_) * sizeof(float);
      aclrtMalloc(&weight_fp32_data_, fp32_bytes, ACL_MEM_MALLOC_NORMAL_ONLY);

      weight_src_cache_ = ascend::AclTensorCache(
          {static_cast<int64_t>(dim_)}, ascend::ToAclDtype(dtype_), nullptr);
      weight_dst_cache_ = ascend::AclTensorCache({static_cast<int64_t>(dim_)},
                                                 ACL_FLOAT, weight_fp32_data_);
    }
  }

  ~Operator() {
    if (!ascend::IsAclRuntimeAlive()) return;

    // Null cached descriptors — see `AclTensorCache::release()`.
    weight_src_cache_.release();
    weight_dst_cache_.release();

    if (weight_fp32_data_) aclrtFree(weight_fp32_data_);
  }

  void operator()(const Tensor input, const Tensor other, const Tensor weight,
                  float eps, Tensor out, Tensor residual_out) const override {
    auto stream = static_cast<aclrtStream>(stream_);

    void* weight_fp32;

    if (dtype_ != DataType::kFloat32) {
      const void* cur_weight = weight.data();

      // Model weights are fixed after loading, so the cast typically runs
      // once on the first call and is skipped on all subsequent calls.
      if (cur_weight != last_weight_ptr_) {
        auto t_src = weight_src_cache_.get(const_cast<void*>(cur_weight));
        auto t_dst = weight_dst_cache_.get(weight_fp32_data_);

        if (!cast_exec_) {
          aclnnCastGetWorkspaceSize(t_src, ACL_FLOAT, t_dst, &cast_ws_,
                                    &cast_exec_);
          aclSetAclOpExecutorRepeatable(cast_exec_);
        } else {
          aclSetInputTensorAddr(cast_exec_, 0, t_src,
                                const_cast<void*>(cur_weight));
          aclSetOutputTensorAddr(cast_exec_, 0, t_dst, weight_fp32_data_);
        }

        auto& arena = ascend::GetWorkspacePool().Ensure(stream, cast_ws_);
        aclnnCast(arena.buf, cast_ws_, cast_exec_, stream);
        last_weight_ptr_ = cur_weight;
      }

      weight_fp32 = weight_fp32_data_;
    } else {
      weight_fp32 = const_cast<void*>(weight.data());
    }

    // Block-level tiling.  Ascend 910B has 20–40 AIV cores; over-subscribing
    // is safe (runtime multiplexes) but wastes one weight load per block.
    static constexpr int64_t kMaxBlockDim = 40;
    int64_t used_cores = std::min(total_rows_, kMaxBlockDim);
    int64_t former_length = (total_rows_ + used_cores - 1) / used_cores;
    int64_t tail_length = former_length - 1;
    int64_t former_num = total_rows_ - tail_length * used_cores;
    uint32_t block_dim = static_cast<uint32_t>(used_cores);

    aclrtlaunch_add_rms_norm(block_dim, stream, const_cast<void*>(input.data()),
                             const_cast<void*>(other.data()), weight_fp32,
                             out.data(), residual_out.data(), total_rows_,
                             static_cast<int64_t>(dim_), dim_length_align_,
                             former_num, former_length, tail_length, eps,
                             static_cast<int64_t>(dtype_));
  }

 private:
  DataType dtype_;

  int64_t dim_length_align_;

  int64_t total_rows_;

  void* weight_fp32_data_ = nullptr;

  mutable ascend::AclTensorCache weight_src_cache_;

  mutable ascend::AclTensorCache weight_dst_cache_;

  mutable const void* last_weight_ptr_ = nullptr;

  mutable aclOpExecutor* cast_exec_ = nullptr;

  mutable uint64_t cast_ws_ = 0;
};

}  // namespace infini::ops

#endif  // INFINI_HAS_CUSTOM_KERNELS
#endif  // INFINI_OPS_ASCEND_ADD_RMS_NORM_KERNEL_CUSTOM_H_
